### ISSUE TITLE
Missing data files required for budapest_connectome_eda.ipynb

### ISSUE THREAD

**Issue by pmzmro** [shayanshafquat/neuronal-oscillations-evolving-networks#1]
This line defines a file path but the data file is not in the repository: 
https://github.com/shayanshafquat/PBM2/blob/3bdbf452a41bfa0e22fbf9e372bc9d0d9d4a39f1/notebooks/budapest_connectome_eda.ipynb#L69

Probably other missing data files required here.

**Comment by shayanshafquat** [comment]
These files are huge, so I avoid pushing them to the remote repository. I have added them to the [drive folder here](https://uniofnottm-my.sharepoint.com/personal/lpxss13_nottingham_ac_uk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Flpxss13%5Fnottingham%5Fac%5Fuk%2FDocuments%2FPBM2%2Fdata&view=0). You can download and replace it in your local repository. @pmzmro

**Comment by shayanshafquat** [comment]
Closing this.
